name: chapter13
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  fluro: ^1.5.2
  provide: ^1.0.2
  flutter_easyrefresh: ^1.0.1
  flutter_webview_plugin: ^0.3.10+1
  webview_flutter: ^0.3.19+9
  device_info: ^0.4.1+5
  package_info: ^0.4.0+14
  pull_to_refresh: ^1.5.8
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.6+2
  intl: ^0.16.1
  lpinyin: ^1.0.8
  open_file: ^3.0.1
  url_launcher: ^5.4.2
  connectivity: ^0.4.8+1
  photo_view: ^0.9.2
  fluttertoast: ^3.1.3
  azlistview: ^0.1.2
  syncfusion_flutter_charts: ^18.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/mock/
    - assets/data/
    - assets/map/

